import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Chatbody from '../components/Chatbody'
export default function Home() {
  return (
    <div >
      <Head>
        <title>chatapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div className="containermain">
    
     <Sidebar />
   
    
     </div>
    </div>
  )
}
